
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 05 11:31:07 CET 2017
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int MINUS = 3;
  public static final int EOF = 0;
}

